// Environment file generation.
// Replaces playbooks/templates/container.env.j2
//
// Output: ~/.config/containers/systemd/{name}.env

use anyhow::Result;
use fsn_node_core::state::desired::ServiceInstance;

/// Generate the .env file content for the given module instance.
/// All Jinja2 vars are already resolved in instance.resolved_env.
pub fn generate(instance: &ServiceInstance) -> Result<String> {
    let mut out = String::new();
    out.push_str(&format!("# Generated by fsn – {}\n", instance.class_key));
    out.push_str("# Do not edit manually – regenerated on every deploy\n\n");

    for (key, value) in &instance.resolved_env {
        out.push_str(&format!("{}={}\n", key, value));
    }

    Ok(out)
}

/// Return the canonical env file path for the given instance name.
pub fn env_path(instance_name: &str) -> std::path::PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
    std::path::PathBuf::from(format!(
        "{}/.config/containers/systemd/{}.env",
        home, instance_name
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;
    use indexmap::IndexMap;
    use fsn_node_core::{
        config::service::{
            Constraints, ContainerDef, ServiceClass, ServiceContract,
            ServiceLoad, ServiceMeta, ServiceSetup, ServiceType,
        },
        state::desired::ServiceInstance,
    };

    fn make_instance(name: &str, class_key: &str, env: HashMap<String, String>) -> ServiceInstance {
        ServiceInstance {
            name: name.to_string(),
            class_key: class_key.to_string(),
            class: ServiceClass {
                meta: ServiceMeta {
                    name: name.to_string(),
                    alias: vec![],
                    service_types: vec![ServiceType::Git],
                    author: None,
                    version: "1.0".to_string(),
                    tags: vec![],
                    description: None,
                    website: None,
                    repository: None,
                    port: 3000,
                    constraints: Constraints::default(),
                    federation: None,
                    health_path: None,
                    health_port: None,
                    health_scheme: None,
                    capabilities: vec![],
                roles: Default::default(),
                ui: Default::default(),
                },
                vars: IndexMap::default(),
                load: ServiceLoad::default(),
                container: ContainerDef {
                    name: name.to_string(),
                    image: format!("docker.io/{name}"),
                    image_tag: "latest".to_string(),
                    networks: vec![],
                    volumes: vec![],
                    published_ports: vec![],
                    healthcheck: None,
                    user: None,
                    read_only: false,
                    tmpfs: vec![],
                    security_opt: vec![],
                    ulimits: IndexMap::default(),
                },
                environment: IndexMap::default(),
                setup: ServiceSetup::default(),
                contract: ServiceContract::default(),
                manifest: None,
            },
            service_types: vec![ServiceType::Git],
            resolved_env: env,
            service_domain: format!("{name}.example.com"),
            alias_domains: vec![],
            sub_services: vec![],
            version: "1.0".to_string(),
            resolved_volumes: vec![],
            capabilities: vec![],
        }
    }

    #[test]
    fn env_file_contains_key_value_pairs() {
        let mut env = HashMap::new();
        env.insert("GIT_HOST".to_string(), "forgejo".to_string());
        env.insert("GIT_PORT".to_string(), "3000".to_string());
        let out = generate(&make_instance("forgejo", "git/forgejo", env)).unwrap();
        assert!(out.contains("GIT_HOST=forgejo"));
        assert!(out.contains("GIT_PORT=3000"));
    }

    #[test]
    fn env_file_has_header_with_class_key() {
        let out = generate(&make_instance("forgejo", "git/forgejo", HashMap::new())).unwrap();
        assert!(out.contains("# Generated by fsn"));
        assert!(out.contains("git/forgejo"));
    }

    #[test]
    fn env_file_is_empty_for_no_env_vars() {
        let out = generate(&make_instance("forgejo", "git/forgejo", HashMap::new())).unwrap();
        // Header exists but no KEY=VALUE lines beyond it
        let non_comment_lines: Vec<_> = out.lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .collect();
        assert!(non_comment_lines.is_empty());
    }
}
