// Quadlet unit file generation.
// Replaces playbooks/templates/container.quadlet.j2 + generate-quadlet.yml
//
// Output: ~/.config/containers/systemd/{name}.container
// (Podman Quadlet format, picked up by systemd after daemon-reload)

use anyhow::Result;
use fsn_node_core::state::desired::ServiceInstance;

/// Generate a Podman Quadlet .container unit file for the given instance.
///
/// `project_network` – the name of the shared project network Quadlet
///   (e.g. "fsn-myproject"). Injected automatically by the deploy engine.
pub fn generate(instance: &ServiceInstance, project_network: Option<&str>) -> Result<String> {
    let c = &instance.class.container;
    let mut out = String::new();

    out.push_str("# Generated by fsn – do not edit manually\n");
    out.push_str(&format!("# Module: {}\n\n", instance.class_key));

    out.push_str("[Unit]\n");
    out.push_str(&format!("Description=FreeSynergy.Node – {}\n", instance.name));
    out.push_str("After=network-online.target\n");
    out.push_str("Wants=network-online.target\n\n");

    out.push_str("[Container]\n");
    out.push_str(&format!("ContainerName={}\n", instance.name));
    out.push_str(&format!("Image={}:{}\n", c.image, c.image_tag));

    // Environment file (always alongside the .container file)
    out.push_str(&format!(
        "EnvironmentFile=%h/.config/containers/systemd/{}.env\n",
        instance.name
    ));

    // User (optional – run as specific UID:GID)
    if let Some(user) = &c.user {
        out.push_str(&format!("User={}\n", user));
    }

    // Project network (injected by deploy engine so containers see each other)
    if let Some(net) = project_network {
        out.push_str(&format!("Network={}.network\n", net));
    }

    // Additional networks declared in the module
    for network in &c.networks {
        out.push_str(&format!("Network={}\n", network));
    }

    // Use resolved_volumes (Jinja2-expanded) when available; fall back to raw
    // class volumes for backward compatibility with non-deploy contexts.
    let volumes: &[String] = if !instance.resolved_volumes.is_empty() {
        &instance.resolved_volumes
    } else {
        &c.volumes
    };
    for volume in volumes {
        out.push_str(&format!("Volume={}\n", volume));
    }

    for port in &c.published_ports {
        out.push_str(&format!("PublishPort={}\n", port));
    }

    if c.read_only {
        out.push_str("ReadOnly=true\n");
    }

    for tmpfs in &c.tmpfs {
        out.push_str(&format!("Tmpfs={}\n", tmpfs));
    }

    for opt in &c.security_opt {
        out.push_str(&format!("SecurityLabelDisable={}\n", opt));
    }

    if let Some(hc) = &c.healthcheck {
        out.push_str(&format!("HealthCmd={}\n", hc.cmd));
        out.push_str(&format!("HealthInterval={}\n", hc.interval));
        out.push_str(&format!("HealthTimeout={}\n", hc.timeout));
        out.push_str(&format!("HealthRetries={}\n", hc.retries));
        out.push_str(&format!("HealthStartPeriod={}\n", hc.start_period));
    }

    out.push('\n');
    out.push_str("[Service]\n");
    out.push_str("Restart=on-failure\n");
    out.push_str("RestartSec=5s\n\n");

    out.push_str("[Install]\n");
    out.push_str("WantedBy=default.target\n");

    Ok(out)
}

/// Generate a Podman Quadlet .network unit file for the shared project network.
pub fn generate_network(_network_name: &str, project_name: &str) -> String {
    format!(
        "# Generated by fsn – shared project network\n\
         [Network]\n\
         Label=fsn.project={project_name}\n"
    )
}

/// Return the canonical Quadlet .container path for the given instance.
pub fn quadlet_path(instance_name: &str) -> std::path::PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
    std::path::PathBuf::from(format!(
        "{}/.config/containers/systemd/{}.container",
        home, instance_name
    ))
}

/// Return the path for the project .network Quadlet file.
pub fn network_path(network_name: &str) -> std::path::PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
    std::path::PathBuf::from(format!(
        "{}/.config/containers/systemd/{}.network",
        home, network_name
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;
    use indexmap::IndexMap;
    use fsn_node_core::{
        config::service::{
            Constraints, ContainerDef, HealthCheck, ServiceClass, ServiceContract,
            ServiceLoad, ServiceMeta, ServiceSetup, ServiceType,
        },
        state::desired::ServiceInstance,
    };

    fn make_instance(name: &str, with_healthcheck: bool) -> ServiceInstance {
        ServiceInstance {
            name: name.to_string(),
            class_key: format!("git/{name}"),
            class: ServiceClass {
                meta: ServiceMeta {
                    name: name.to_string(),
                    alias: vec![],
                    service_types: vec![ServiceType::Git],
                    author: None,
                    version: "1.0".to_string(),
                    tags: vec![],
                    description: None,
                    website: None,
                    repository: None,
                    port: 3000,
                    constraints: Constraints::default(),
                    federation: None,
                    health_path: Some("/health".to_string()),
                    health_port: None,
                    health_scheme: None,
                    capabilities: vec![],
                roles: Default::default(),
                ui: Default::default(),
                },
                vars: IndexMap::default(),
                load: ServiceLoad::default(),
                container: ContainerDef {
                    name: name.to_string(),
                    image: "ghcr.io/forgejo/forgejo".to_string(),
                    image_tag: "9".to_string(),
                    networks: vec![],
                    volumes: vec!["/data/forgejo:/data".to_string()],
                    published_ports: vec![],
                    healthcheck: if with_healthcheck {
                        Some(HealthCheck {
                            cmd: "curl -f http://localhost:3000/health".to_string(),
                            interval: "30s".to_string(),
                            timeout: "10s".to_string(),
                            retries: 3,
                            start_period: "60s".to_string(),
                        })
                    } else {
                        None
                    },
                    user: Some("1000".to_string()),
                    read_only: true,
                    tmpfs: vec!["/tmp".to_string()],
                    security_opt: vec![],
                    ulimits: IndexMap::default(),
                },
                environment: IndexMap::default(),
                setup: ServiceSetup::default(),
                contract: ServiceContract::default(),
                manifest: None,
            },
            service_types: vec![ServiceType::Git],
            resolved_env: HashMap::new(),
            service_domain: format!("{name}.example.com"),
            alias_domains: vec![],
            sub_services: vec![],
            version: "1.0".to_string(),
            resolved_volumes: vec!["/opt/data/forgejo:/data".to_string()],
            capabilities: vec![],
        }
    }

    #[test]
    fn quadlet_contains_unit_section() {
        let out = generate(&make_instance("forgejo", false), None).unwrap();
        assert!(out.contains("[Unit]"));
        assert!(out.contains("Description=FreeSynergy.Node – forgejo"));
        assert!(out.contains("After=network-online.target"));
    }

    #[test]
    fn quadlet_contains_container_fields() {
        let out = generate(&make_instance("forgejo", false), None).unwrap();
        assert!(out.contains("[Container]"));
        assert!(out.contains("ContainerName=forgejo"));
        assert!(out.contains("Image=ghcr.io/forgejo/forgejo:9"));
        assert!(out.contains("User=1000"));
        assert!(out.contains("ReadOnly=true"));
    }

    #[test]
    fn quadlet_injects_project_network() {
        let out = generate(&make_instance("forgejo", false), Some("fsn-myproject")).unwrap();
        assert!(out.contains("Network=fsn-myproject.network"));
    }

    #[test]
    fn quadlet_no_network_when_none() {
        let out = generate(&make_instance("forgejo", false), None).unwrap();
        assert!(!out.contains("Network="));
    }

    #[test]
    fn quadlet_uses_resolved_volumes_over_class_volumes() {
        let out = generate(&make_instance("forgejo", false), None).unwrap();
        assert!(out.contains("Volume=/opt/data/forgejo:/data"));
        assert!(!out.contains("Volume=/data/forgejo:/data"));
    }

    #[test]
    fn quadlet_contains_healthcheck() {
        let out = generate(&make_instance("forgejo", true), None).unwrap();
        assert!(out.contains("HealthCmd=curl -f http://localhost:3000/health"));
        assert!(out.contains("HealthInterval=30s"));
        assert!(out.contains("HealthTimeout=10s"));
        assert!(out.contains("HealthRetries=3"));
        assert!(out.contains("HealthStartPeriod=60s"));
    }

    #[test]
    fn quadlet_no_healthcheck_section_when_absent() {
        let out = generate(&make_instance("forgejo", false), None).unwrap();
        assert!(!out.contains("HealthCmd="));
    }

    #[test]
    fn quadlet_contains_service_and_install_sections() {
        let out = generate(&make_instance("forgejo", false), None).unwrap();
        assert!(out.contains("[Service]"));
        assert!(out.contains("Restart=on-failure"));
        assert!(out.contains("[Install]"));
        assert!(out.contains("WantedBy=default.target"));
    }

    #[test]
    fn generate_network_contains_project_label() {
        let out = generate_network("fsn-myproject", "myproject");
        assert!(out.contains("[Network]"));
        assert!(out.contains("Label=fsn.project=myproject"));
    }
}
