// Quadlet unit file generation.
// Replaces playbooks/templates/container.quadlet.j2 + generate-quadlet.yml
//
// Output: ~/.config/containers/systemd/{name}.container
// (Podman Quadlet format, picked up by systemd after daemon-reload)

use anyhow::Result;
use fsn_core::state::desired::ServiceInstance;

/// Generate a Podman Quadlet .container unit file for the given instance.
///
/// `project_network` – the name of the shared project network Quadlet
///   (e.g. "fsn-myproject"). Injected automatically by the deploy engine.
pub fn generate(instance: &ServiceInstance, project_network: Option<&str>) -> Result<String> {
    let c = &instance.class.container;
    let mut out = String::new();

    out.push_str("# Generated by fsn – do not edit manually\n");
    out.push_str(&format!("# Module: {}\n\n", instance.class_key));

    out.push_str("[Unit]\n");
    out.push_str(&format!("Description=FreeSynergy.Node – {}\n", instance.name));
    out.push_str("After=network-online.target\n");
    out.push_str("Wants=network-online.target\n\n");

    out.push_str("[Container]\n");
    out.push_str(&format!("ContainerName={}\n", instance.name));
    out.push_str(&format!("Image={}:{}\n", c.image, c.image_tag));

    // Environment file (always alongside the .container file)
    out.push_str(&format!(
        "EnvironmentFile=%h/.config/containers/systemd/{}.env\n",
        instance.name
    ));

    // User (optional – run as specific UID:GID)
    if let Some(user) = &c.user {
        out.push_str(&format!("User={}\n", user));
    }

    // Project network (injected by deploy engine so containers see each other)
    if let Some(net) = project_network {
        out.push_str(&format!("Network={}.network\n", net));
    }

    // Additional networks declared in the module
    for network in &c.networks {
        out.push_str(&format!("Network={}\n", network));
    }

    // Use resolved_volumes (Jinja2-expanded) when available; fall back to raw
    // class volumes for backward compatibility with non-deploy contexts.
    let volumes: &[String] = if !instance.resolved_volumes.is_empty() {
        &instance.resolved_volumes
    } else {
        &c.volumes
    };
    for volume in volumes {
        out.push_str(&format!("Volume={}\n", volume));
    }

    for port in &c.published_ports {
        out.push_str(&format!("PublishPort={}\n", port));
    }

    if c.read_only {
        out.push_str("ReadOnly=true\n");
    }

    for tmpfs in &c.tmpfs {
        out.push_str(&format!("Tmpfs={}\n", tmpfs));
    }

    for opt in &c.security_opt {
        out.push_str(&format!("SecurityLabelDisable={}\n", opt));
    }

    if let Some(hc) = &c.healthcheck {
        out.push_str(&format!("HealthCmd={}\n", hc.cmd));
        out.push_str(&format!("HealthInterval={}\n", hc.interval));
        out.push_str(&format!("HealthTimeout={}\n", hc.timeout));
        out.push_str(&format!("HealthRetries={}\n", hc.retries));
        out.push_str(&format!("HealthStartPeriod={}\n", hc.start_period));
    }

    out.push('\n');
    out.push_str("[Service]\n");
    out.push_str("Restart=on-failure\n");
    out.push_str("RestartSec=5s\n\n");

    out.push_str("[Install]\n");
    out.push_str("WantedBy=default.target\n");

    Ok(out)
}

/// Generate a Podman Quadlet .network unit file for the shared project network.
pub fn generate_network(_network_name: &str, project_name: &str) -> String {
    format!(
        "# Generated by fsn – shared project network\n\
         [Network]\n\
         Label=fsn.project={project_name}\n"
    )
}

/// Return the canonical Quadlet .container path for the given instance.
pub fn quadlet_path(instance_name: &str) -> std::path::PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
    std::path::PathBuf::from(format!(
        "{}/.config/containers/systemd/{}.container",
        home, instance_name
    ))
}

/// Return the path for the project .network Quadlet file.
pub fn network_path(network_name: &str) -> std::path::PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
    std::path::PathBuf::from(format!(
        "{}/.config/containers/systemd/{}.network",
        home, network_name
    ))
}
