// fsn-form – backend-agnostic form schema layer.
//
// Architecture (three-layer, HTML-inspired):
//
//   Domain struct   ──▶  #[derive(Form)]  ──▶  FormSchema (static, compile-time)
//   FormSchema      ──▶  build_nodes()    ──▶  Vec<Box<dyn FormNode>>  (TUI)
//   FormSchema      ──▶  WebRenderer      ──▶  HTML <form>             (future)
//   FormSchema      ──▶  CliRenderer      ──▶  inquire prompts         (future)
//
// A FormSchema is generated once at startup (via OnceLock) and shared
// immutably across the entire application lifetime.

// Re-export the proc-macro so consumers only need `fsn-form` in Cargo.toml.
pub use fsn_form_derive::Form;

// ── Widget types ──────────────────────────────────────────────────────────────

/// The UI control type for a field.
///
/// The renderer maps each variant to a concrete FormNode implementation.
/// New widget types can be added here without touching existing FormNode code.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WidgetType {
    /// Single-line text input.
    Text,
    /// Masked single-line input — value is hidden while typing.
    Password,
    /// Single-line input with email validation.
    Email,
    /// Single-line input with IPv4/IPv6 validation.
    IpAddress,
    /// Drop-down list — exactly one option selected.
    Select,
    /// Checkbox list — zero or more options selected (stored as comma-separated).
    MultiSelect,
    /// On/off toggle (bool field, stored as "true"/"false").
    Toggle,
    /// Integer or float input.
    Number,
    /// Multi-line text area. Height controlled by `FieldMeta::rows`.
    TextArea,
    /// Editable key-value-comment table for environment variables.
    EnvTable,
}

// ── FieldMeta ─────────────────────────────────────────────────────────────────

/// Static description of a single form field.
///
/// Generated by `#[derive(Form)]` and stored in a global `OnceLock<FormSchema>`.
/// Never mutated at runtime — all mutable state lives in the renderer's node layer.
#[derive(Debug, Clone)]
pub struct FieldMeta {
    /// Unique field key within the form — matches the struct field name.
    pub key: &'static str,

    /// i18n lookup key for the label shown above the input.
    pub label_key: &'static str,

    /// i18n lookup key for the hint line below the input. `None` = no hint.
    pub hint_key: Option<&'static str>,

    /// UI control type — determines which FormNode implementation is used.
    pub widget: WidgetType,

    /// Whether the field must be non-empty to submit the form.
    pub required: bool,

    /// Zero-based tab index for multi-tab forms.
    pub tab: usize,

    /// Maximum number of characters (applies to text-like widgets).
    pub max_len: Option<usize>,
    /// Visible row count for `TextArea` widgets (default: 4 when `None`).
    pub rows: Option<u16>,

    /// Static default value shown when the field is first opened.
    pub default_val: Option<&'static str>,

    /// Available choices for `Select` and `MultiSelect` widgets.
    /// Each entry is the stored value (not the display label).
    pub options: Vec<&'static str>,
}

// ── FormSchema ────────────────────────────────────────────────────────────────

/// Static description of all fields in a form.
///
/// Returned by `Form::schema()` — created once per type (via `OnceLock`)
/// and reused for every new/edit instance of that form.
#[derive(Debug, Clone)]
pub struct FormSchema {
    /// All fields in declaration order.
    pub fields: Vec<FieldMeta>,
}

impl FormSchema {
    /// Returns all field descriptors for a given tab index.
    pub fn fields_for_tab(&self, tab: usize) -> impl Iterator<Item = &FieldMeta> {
        self.fields.iter().filter(move |f| f.tab == tab)
    }

    /// Returns the number of distinct tabs (0 when there are no fields).
    pub fn tab_count(&self) -> usize {
        self.fields.iter().map(|f| f.tab + 1).max().unwrap_or(0)
    }

    /// Look up a field descriptor by key. Returns `None` when not found.
    pub fn field(&self, key: &str) -> Option<&FieldMeta> {
        self.fields.iter().find(|f| f.key == key)
    }
}

// ── Form trait ────────────────────────────────────────────────────────────────

/// A type that can describe itself as a form schema.
///
/// Implemented automatically by `#[derive(Form)]`.
///
/// ```
/// use fsn_form::Form;
///
/// #[derive(Form)]
/// struct MyForm {
///     #[form(label = "form.name", required, tab = 0)]
///     name: String,
/// }
///
/// let schema = MyForm::schema();
/// assert_eq!(schema.fields[0].key, "name");
/// ```
pub trait Form: Sized {
    /// Returns the static schema describing all fields.
    ///
    /// The schema is computed once (via `OnceLock`) and shared for the
    /// entire process lifetime. Call this freely — it is zero-cost after
    /// the first call.
    fn schema() -> &'static FormSchema;
}
