#!/usr/bin/env bash
# ==============================================================================
# FreeSynergy.Node – i18n Code Generator
# File:    tools/generate-i18n.sh
# Purpose: Convert locales/*.po files into embedded declare -A _TR_xx=() arrays
#          for inclusion in fsn-install.sh.
# Usage:   bash tools/generate-i18n.sh
# Output:  Prints the declare -A blocks to stdout.
#          To update fsn-install.sh, use: --apply (replaces the embedded section)
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "${SCRIPT_DIR}")"
LOCALES_DIR="${REPO_ROOT}/locales"
INSTALLER="${REPO_ROOT}/fsn-install.sh"

# Markers that bracket the embedded translations section in fsn-install.sh
MARKER_START="# ── Embedded Translations ──"
MARKER_END="# --- Built-in module list"

usage() {
    cat <<EOF
Usage: bash tools/generate-i18n.sh [--apply]

  (no flag)  Print generated declare -A blocks to stdout
  --apply    Replace the embedded translation section in fsn-install.sh
  --help     Show this help

The script reads all locales/*.po files (except en.pot) and generates
bash 'declare -A _TR_<langcode>=([key]="value")' arrays.

To add a new language:
  1. Copy locales/en.pot to locales/<langcode>.po
  2. Fill in all msgstr fields
  3. Run: bash tools/generate-i18n.sh --apply
EOF
}

# Parse a single .po file and emit a bash declare -A block.
# $1 = path to .po file
# $2 = language code (e.g. "de")
generate_array() {
    local po_file="$1"
    local lang="$2"

    echo ""
    echo "# ── ${lang^^} (${lang}) ────────────────────────────────────────────────────────────────────"
    echo "declare -A _TR_${lang}=("

    local msgid="" msgstr="" in_msgid=0 in_msgstr=0

    flush_entry() {
        # Only emit entries where both key and value are non-empty
        if [ -n "${msgid}" ] && [ -n "${msgstr}" ]; then
            # Escape any unescaped double quotes inside the values
            local safe_key="${msgid//\"/\\\"}"
            local safe_val="${msgstr//\"/\\\"}"
            printf '    ["%s"]="%s"\n' "${safe_key}" "${safe_val}"
        fi
        msgid=""
        msgstr=""
        in_msgid=0
        in_msgstr=0
    }

    while IFS= read -r line; do
        # Skip comments and blank lines between entries
        if [[ "${line}" =~ ^# ]] || [ -z "${line}" ]; then
            if [ -n "${msgid}" ] || [ -n "${msgstr}" ]; then
                flush_entry
            fi
            continue
        fi

        if [[ "${line}" =~ ^msgid\ \"(.*)\"$ ]]; then
            if [ -n "${msgid}" ] || [ -n "${msgstr}" ]; then
                flush_entry
            fi
            msgid="${BASH_REMATCH[1]}"
            in_msgid=1
            in_msgstr=0
        elif [[ "${line}" =~ ^msgstr\ \"(.*)\"$ ]]; then
            msgstr="${BASH_REMATCH[1]}"
            in_msgid=0
            in_msgstr=1
        elif [[ "${line}" =~ ^\"(.*)\"$ ]]; then
            # Continuation line
            if [ "${in_msgid}" -eq 1 ]; then
                msgid+="${BASH_REMATCH[1]}"
            elif [ "${in_msgstr}" -eq 1 ]; then
                msgstr+="${BASH_REMATCH[1]}"
            fi
        fi
    done < "${po_file}"

    # Flush last entry
    if [ -n "${msgid}" ] || [ -n "${msgstr}" ]; then
        flush_entry
    fi

    echo ")"
}

generate_all() {
    echo "# ── Embedded Translations ──────────────────────────────────────────────────────────────────"
    echo "# Generated by tools/generate-i18n.sh from locales/*.po"
    echo "# To add/update: edit locales/<lang>.po, then run: bash tools/generate-i18n.sh --apply"

    local found=0
    for po_file in "${LOCALES_DIR}"/*.po; do
        [ -f "${po_file}" ] || continue
        local basename
        basename=$(basename "${po_file}" .po)
        # Skip the template file and the English source
        [[ "${basename}" == "en" ]] && continue

        generate_array "${po_file}" "${basename}"
        found=$((found + 1))
    done

    if [ "${found}" -eq 0 ]; then
        echo "# (no translations found in ${LOCALES_DIR}/)"
    fi
}

apply_to_installer() {
    if [ ! -f "${INSTALLER}" ]; then
        echo "ERROR: Installer not found: ${INSTALLER}" >&2
        exit 1
    fi

    local generated
    generated=$(generate_all)

    # Build the replacement: everything between the two markers
    local tmp
    tmp=$(mktemp)

    local in_block=0
    local replaced=0

    while IFS= read -r line; do
        if [[ "${line}" == *"${MARKER_START}"* ]] && [ "${in_block}" -eq 0 ]; then
            in_block=1
            # Emit the generated block instead of the original content
            printf '%s\n' "${generated}"
            replaced=1
            continue
        fi

        if [ "${in_block}" -eq 1 ]; then
            # Skip lines until we reach the end marker
            if [[ "${line}" == *"${MARKER_END}"* ]]; then
                in_block=0
                printf '%s\n' "${line}"
            fi
            # Lines inside the old block are discarded (replaced by generated)
            continue
        fi

        printf '%s\n' "${line}"
    done < "${INSTALLER}" > "${tmp}"

    if [ "${replaced}" -eq 0 ]; then
        echo "ERROR: Could not find marker '${MARKER_START}' in ${INSTALLER}" >&2
        echo "       The installer may have been modified manually." >&2
        rm -f "${tmp}"
        exit 1
    fi

    mv "${tmp}" "${INSTALLER}"
    echo "[OK] Embedded translations updated in: ${INSTALLER}"
    echo "     Languages: $(cd "${LOCALES_DIR}" && ls ./*.po 2>/dev/null | grep -v '^./en\.po' | sed 's/\.\///;s/\.po//' | tr '\n' ' ')"
}

case "${1:-}" in
    --apply)    apply_to_installer ;;
    --help|-h)  usage ;;
    "")         generate_all ;;
    *)          echo "Unknown option: $1" >&2; usage >&2; exit 1 ;;
esac
